[package]
name = "rust_calculator"
version = "0.1.0"
authors = ["logan-forman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-integer = "0.1.42"